apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: httpd
        name: httpd
